# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Malik|My Blog
subtitle: 个人博客
description: MalikCheng 记录分享时下流行技术
keywords:
author: MalikCheng
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://demo.malik.pub
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:


# Site settings
SEOTitle: 程连龙 | Blog
email: malik.1.cheng@gmail.com
keyword: ""
header-img: https://pic.taifua.com/cdn/common/index.jpg
article-img: /img/article_header/article_bg.jpg
404-img: /img/header_img/404.png
signature: false #show signature
signature-img: img/signature/BeanTechSign-white.png 



menu:
  home: / || home
  about: /about/ || user
  tags: /tags/ || tags
  #categories: /categories/ || th
  archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbea


# SNS settings
# RSS: false
# weibo_username:     
# zhihu_username:     
github_username:        MalikCheng
# twitter_username:   
facebook_username:  Malik Cheng
csdn_username:  https://blog.csdn.net/qq_34291777
#linkedin_username:  


# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`




# Disqus settings
#disqus_username: your-disqus-ID

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
#Baidu Analytics
#a_track_id: r45fhy7653897235wg5ye709d930f62e
# Google Analytics
#ga_track_id: 'UA-XXXXXXXX-X'          # Format: UA-xxxxxx-xx
#a_domain: yoursite


# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "Stay hungry,Stay foolish"
sidebar-avatar: /img/avatar/myavatar.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive


## Archive
archives-img: /img/header_img/archives-widget.jpg
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


## Friends
friends: [
    {
        title: "CSDN Blog ",
        href: "https://blog.csdn.net/qq_34291777"
    },
    {
        title: "gitbub ",
        href: "https://github.com/MalikCheng"
    },

]

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

  
  

  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: article
category_map:
   Docker: docker
#  Golang: golang
#  Database: database

tag_map:
home_posts_tag: true 
# show posts tags


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
    
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huweihuang

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:MalikCheng/myblog.git
  branch : master
  
